name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: your-project-id
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: gcr.io/your-project-id/your-image-name:${{ github.sha }}
        secrets: |
          ${{ secrets.GCR_USERNAME }}=${{ secrets.GCR_PASSWORD }}

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@main
      with:
        image: gcr.io/your-project-id/your-image-name:${{ github.sha }}
        region: your-region
        service_name: your-service-name
        platform: managed
        allow_unauthenticated: true
        project_id: your-project-id
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
