name: Deploy to staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Setup Git
        run: |
          git config user.name "Staging Sync Bot"
          git config user.email "staging-sync-bot@users.noreply.github.com"

      - name: Push to staging
        run: |
          git fetch origin
          git checkout staging
          if git merge --ff-only origin/main; then
            echo "Fast-forward successful. Pushing..."
            git push origin staging
          else
            echo "No fast-forward possible. Skipping push."
          fi
